server:
  port: 8443
  ssl:
    key-store: classpath:sample.jks
    key-store-password: secret
    key-password: password
security:
  oauth2:
    resource:
      filter-order: 3
logging:
  level:
    org:
      springframework:
        web: TRACE